[package]
name = "mcmapper-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anvil-region = "0.8.1"
fastnbt = "2.3.2"
fastanvil = "0.26.0"
simple-anvil = "0.3.3"